# **Exercices Fondamentaux NumPy**

1. Écrivez un programme NumPy pour obtenir la version de NumPy et afficher la configuration de compilation de NumPy.

In [1]:
import numpy as np
print(f"Version de NumPy : {np.__version__}")
print("\nConfiguration de compilation de NumPy :")
print(np.show_config())

Version de NumPy : 2.2.5

Configuration de compilation de NumPy :
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/v

c:\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


2. Écrivez un programme NumPy pour obtenir de l'aide sur la fonction d'addition (add).

In [2]:
print("\nAide sur la fonction d'addition (add) :")
print(help(np.add))


Aide sur la fonction d'addition (add) :
Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc resu

3. Écrivez un programme NumPy pour tester si aucun des éléments d’un tableau donné n’est égal à zéro.

In [3]:
tableau_donne = np.array([1, 2, 3, 4, 5])
print(f"Tableau 1 : {tableau_donne}")
print(f"Aucun élément n'est nul : {np.all(tableau_donne != 0)}")

Tableau 1 : [1 2 3 4 5]
Aucun élément n'est nul : True


4. Écrivez un programme NumPy pour tester si un des éléments d’un tableau donné est non nul.

In [4]:
tableau_donne = np.array([0, 0, 3, 0, 0])
print(f"Tableau 1 : {tableau_donne}")
print(f"Des éléments sont non nuls : {np.any(tableau_donne != 0)}")

Tableau 1 : [0 0 3 0 0]
Des éléments sont non nuls : True


5. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont finies (ni infinies, ni NaN).

In [5]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test de finitude (isinf ou isnan sont Faux) : {np.isfinite(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test de finitude (isinf ou isnan sont Faux) : [ True  True False False False  True]


6. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs sont infinies (positives ou négatives).

In [6]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test d'infini (isinf) : {np.isinf(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test d'infini (isinf) : [False False False  True  True False]


7. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont des NaN (Not a Number).

In [7]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test de NaN (isnan) : {np.isnan(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test de NaN (isnan) : [False False  True False False False]


8. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont complexes ou réelles. Testez aussi si une valeur donnée est un scalaire.

In [8]:
tableau_donne = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(f"Tableau : {tableau_donne}")
print(f"Test de complexité (iscomplex) : {np.iscomplex(tableau_donne)}")
print(f"Test de réels (isreal) : {np.isreal(tableau_donne)}")
# Test de scalaires pour chaque élément
print(f"Test de scalaires (isscalar) : {[np.isscalar(x) for x in tableau_donne]}")

Tableau : [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Test de complexité (iscomplex) : [ True False False False False  True]
Test de réels (isreal) : [False  True  True  True  True False]
Test de scalaires (isscalar) : [True, True, True, True, True, True]


9. Écrivez un programme NumPy pour tester si deux tableaux sont égaux, élément par élément, dans une certaine tolérance.

In [9]:
print("Tester si deux tableaux sont égaux élément par élément avec une tolérance :")
tableau1 = np.array([1.0, 2.0, 3.0])
tableau2 = np.array([1.0, 2.0, 3.0001])
tolerance = 0.001
print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")
print(f"Égalité avec tolérance {tolerance} : {np.allclose(tableau1, tableau2, atol=tolerance)}")

Tester si deux tableaux sont égaux élément par élément avec une tolérance :
Tableau 1 : [1. 2. 3.]
Tableau 2 : [1.     2.     3.0001]
Égalité avec tolérance 0.001 : True


10. Écrivez un programme NumPy pour effectuer une comparaison élémentaire (supérieur, supérieur_ou_égal, inférieur, inférieur_ou_égal) entre deux tableaux.

In [10]:
tableau1 = np.array([1, 2, 3])
tableau2 = np.array([4, 5, 6])
print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")
print(f"Supérieur : {np.greater(tableau1, tableau2)}")
print(f"Supérieur ou égal : {np.greater_equal(tableau1, tableau2)}")
print(f"Inferieur : {np.less(tableau1, tableau2)}")
print(f"Inferieur ou égal : {np.less_equal(tableau1, tableau2)}")

Tableau 1 : [1 2 3]
Tableau 2 : [4 5 6]
Supérieur : [False False False]
Supérieur ou égal : [False False False]
Inferieur : [ True  True  True]
Inferieur ou égal : [ True  True  True]


11. Écrivez un programme NumPy pour effectuer une comparaison élémentaire (égalité stricte ou dans une tolérance) entre deux tableaux.

In [11]:
tableau1 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
tableau2 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")

print(f"Égalité stricte : {np.array_equal(tableau1, tableau2)}")

tolerance = 0.00001
print(f"Égalité avec tolérance {tolerance} : {np.allclose(tableau1, tableau2, atol=tolerance)}")

Tableau 1 : [  72   79   85   90  150 -135  120  -10   60  100]
Tableau 2 : [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Égalité stricte : False
Égalité avec tolérance 1e-05 : True


12. Écrivez un programme NumPy pour créer un tableau avec les valeurs 1, 7, 13, 105 et déterminer la taille mémoire qu’il occupe.

In [12]:
tableau = np.array([1, 7, 13, 105])
print(f"Tableau : {tableau}")
print(f"Taille mémoire occupée : {tableau.nbytes} octets")

Tableau : [  1   7  13 105]
Taille mémoire occupée : 32 octets


13. Écrivez un programme NumPy pour créer un tableau de 10 zéros, un autre de 10 uns, et un autre de 10 cinq.

In [13]:
tableau_zeros = np.zeros(10)
tableau_uns = np.ones(10)
tableau_cinq = np.full(10, 5.) # Ou bien np.ones(10) * 5
print(f"Tableau de 10 zéros : {tableau_zeros}")
print(f"Tableau de 10 uns : {tableau_uns}")
print(f"Tableau de 10 cinq : {tableau_cinq}")

Tableau de 10 zéros : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tableau de 10 uns : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Tableau de 10 cinq : [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Écrivez un programme NumPy pour créer un tableau contenant les entiers de 30 à 70.

In [14]:
tableau = np.arange(30, 71)
print(f"Tableau contenant les entiers de 30 à 70 : {tableau}")

Tableau contenant les entiers de 30 à 70 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15. Écrivez un programme NumPy pour créer un tableau contenant uniquement les entiers pairs de 30 à 70.

In [15]:
tableau = np.arange(30, 71, 2)
print(f"Tableau contenant les entiers pairs de 30 à 70 : {tableau}")

Tableau contenant les entiers pairs de 30 à 70 : [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Écrivez un programme NumPy pour créer une matrice identité 3x3.

In [16]:
matrice_identite = np.identity(3)
print(f"Matrice identité 3x3 :\n{matrice_identite}")

Matrice identité 3x3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Écrivez un programme NumPy pour générer un nombre aléatoire entre 0 et 1.

In [17]:
nombre_aleatoire = np.random.normal(0,1, 1)
print(f"Nombre aléatoire entre 0 et 1 : {nombre_aleatoire}")

Nombre aléatoire entre 0 et 1 : [0.14360854]


18. Écrivez un programme NumPy pour générer un tableau de 15 nombres aléatoires selon une distribution normale standard.

In [18]:
nombre_aleatoire = np.random.normal(0,1, 15)
print(f"Tableau de 15 nombres aléatoires selon une distribution normale standard : {nombre_aleatoire}")

Tableau de 15 nombres aléatoires selon une distribution normale standard : [ 1.26575987 -0.6458258  -0.46229754 -0.84657785  1.79109479 -0.27052407
  1.08195813 -1.1235229  -1.73879563 -0.6302348  -2.03148741  0.06376206
  2.40199658  0.27502929  0.38907747]


19. Écrivez un programme NumPy pour créer un vecteur de valeurs de 15 à 55, en affichant toutes sauf la première et la dernière.

In [19]:
vecteur = np.arange(15, 56)
print(f"Vecteur de valeurs de 15 à 55 : {vecteur}")

vecteur_sans_premier_dernier = vecteur[1:-1]
print(f"Vecteur sans le premier et le dernier élément : {vecteur_sans_premier_dernier}")

Vecteur de valeurs de 15 à 55 : [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Vecteur sans le premier et le dernier élément : [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20. Écrivez un programme NumPy pour créer un tableau 3x4 et itérer sur ses éléments.

In [20]:
tableau = np.arange(10,22).reshape((3, 4))
print(f"Tableau 3x4 :\n{tableau}")

print("Itération sur les éléments du tableau 3x4 :")
for i in np.nditer(tableau):
    print(i, end=' ')

Tableau 3x4 :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Itération sur les éléments du tableau 3x4 :
10 11 12 13 14 15 16 17 18 19 20 21 

21. Écrivez un programme NumPy pour créer un vecteur de longueur 10, contenant des valeurs réparties uniformément entre 5 et 50.

In [21]:
vecteur = np.linspace(5,50,10)
print(f"Vecteur de 5 à 50 avec 10 points : {vecteur}")

Vecteur de 5 à 50 avec 10 points : [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


22. Écrivez un programme NumPy pour créer un vecteur allant de 0 à 20, et inverser le signe des nombres entre 9 et 15.

In [22]:
vecteur = np.arange(21)
print(f"Vecteur de 0 à 20 : {vecteur}")
vecteur[9:16] = -vecteur[9:16]
print(f"Vecteur apres inversion des signes entre 9 et 15 : {vecteur}")

Vecteur de 0 à 20 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Vecteur apres inversion des signes entre 9 et 15 : [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Écrivez un programme NumPy pour créer un vecteur de longueur 5 rempli d’entiers aléatoires entre 0 et 10.

In [23]:
vecteur = np.random.randint(0, 11, 5)
print(f"Vecteur de longueur 5 rempli d’entiers aléatoires entre 0 et 10 : {vecteur}")

Vecteur de longueur 5 rempli d’entiers aléatoires entre 0 et 10 : [ 5  5 10  0  5]


24. Écrivez un programme NumPy pour multiplier les valeurs de deux vecteurs donnés.

In [24]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f"Vecteur x : {x}")
print(f"Vecteur y : {y}")

resultat = x*y
print(f"Produit élément par élément de x et y : {resultat}")

Vecteur x : [1 2 3]
Vecteur y : [4 5 6]
Produit élément par élément de x et y : [ 4 10 18]


25. Écrivez un programme NumPy pour créer une matrice 3x4 remplie avec les valeurs de 10 à 21.

In [25]:
matrice = np.arange(10, 22).reshape((3, 4))
print(f"Matrice 3x4 :\n{matrice}")

Matrice 3x4 :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26. Écrivez un programme NumPy pour trouver le nombre de lignes et de colonnes dans une matrice donnée.

In [26]:
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print(f"Matrice :\n{matrice}")
lignes, colonnes = matrice.shape
print(f"\nNombre de lignes : {lignes}, Nombre de colonnes : {colonnes}")

Matrice :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Nombre de lignes : 4, Nombre de colonnes : 3


27. Écrivez un programme NumPy pour créer une matrice 3x3 identité (diagonale à 1, reste à 0).

In [27]:
matrice_identite = np.identity(3)
print(f"Matrice identité 3x3 :\n{matrice_identite}")

Matrice identité 3x3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


28. Écrivez un programme NumPy pour créer une matrice 10x10 dont la bordure contient des 1 et l’intérieur des 0.

In [28]:
matrice = np.ones((10, 10))
matrice[1:-1, 1:-1] = 0
print(f"Matrice 10x10 avec bordure de 1 et intérieur de 0 :\n{matrice}")

Matrice 10x10 avec bordure de 1 et intérieur de 0 :
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


29. Écrivez un programme NumPy pour créer une matrice 5x5 remplie de zéros avec une diagonale principale contenant les valeurs 1 à 5.

In [29]:
matrice = np.diag(np.arange(1, 6))
print(f"Matrice diagonale 5x5 :\n{matrice}")

Matrice diagonale 5x5 :
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


30. Écrivez un programme NumPy pour créer une matrice 4x4 avec alternance de 0 et 1, les diagonales principales étant à 0.

In [30]:
matrice = np.zeros((4, 4), dtype=int)
matrice[1::2, ::2] = 1
print(f"Matrice 4x4 avec alternance de 0 et 1, diagonales principales à 0 :\n{matrice}")

Matrice 4x4 avec alternance de 0 et 1, diagonales principales à 0 :
[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [1 0 1 0]]


31. Écrivez un programme NumPy pour créer un tableau tridimensionnel 3x3x3 rempli de valeurs arbitraires.

In [31]:
matrice = np.random.random((3, 3, 3))
print(f"Tableau tridimensionnel 3x3x3 rempli de valeurs arbitraires :\n{matrice}")

Tableau tridimensionnel 3x3x3 rempli de valeurs arbitraires :
[[[0.29009937 0.32554994 0.66004511]
  [0.04157973 0.23759925 0.4484368 ]
  [0.849225   0.05882643 0.24965931]]

 [[0.79190635 0.03860721 0.53268053]
  [0.33609024 0.99788545 0.1904074 ]
  [0.70696866 0.95819829 0.99237642]]

 [[0.76373695 0.65653292 0.44401769]
  [0.65372052 0.76031992 0.39041366]
  [0.41743232 0.48497626 0.60483806]]]


32. Écrivez un programme NumPy pour calculer la somme de tous les éléments, la somme par colonne et la somme par ligne dans un tableau donné.

In [32]:
tableau = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print(f"Tableau 4x3 :\n{tableau}")
print(f"La somme de tous les éléments : {np.sum(tableau)}")
print(f"La somme de chaque colonne : {np.sum(tableau, axis=0)}")
print(f"La somme de chaque ligne : {np.sum(tableau, axis=1)}")

Tableau 4x3 :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
La somme de tous les éléments : 78
La somme de chaque colonne : [22 26 30]
La somme de chaque ligne : [ 6 15 24 33]


33. Écrivez un programme NumPy pour calculer le produit scalaire de deux vecteurs donnés.

In [33]:
vecteur1 = np.array([1, 2, 3])
vecteur2 = np.array([4, 5, 6])
produit_scalaire = np.dot(vecteur1, vecteur2)
print(f"Produit scalaire de {vecteur1} et {vecteur2} : {produit_scalaire}")

Produit scalaire de [1 2 3] et [4 5 6] : 32


34. Écrivez un programme NumPy pour ajouter un vecteur à chaque ligne d'une matrice donnée.

In [34]:
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])
vecteur_ajout = np.array([1, 2, 3])
matrice_ajoutee = matrice + vecteur_ajout
print(f"Matrice 4x3 après ajout du vecteur {vecteur_ajout} :\n{matrice_ajoutee}")

Matrice 4x3 après ajout du vecteur [1 2 3] :
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


35. Écrivez un programme NumPy pour détecter les valeurs manquantes (NaN) dans un tableau donné.

In [35]:
matrice = np.array([[1, 2, 3],
                                [4, np.nan, 6],
                                [7, 8, 9],
                                [10, 11, 12]])

print(f"Matrice : \n{matrice}")
print(f"Les vaaleurs manquantes (NaN) dans le tableau sont : {np.isnan(matrice)}")


Matrice : 
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Les vaaleurs manquantes (NaN) dans le tableau sont : [[False False False]
 [False  True False]
 [False False False]
 [False False False]]


36. Écrivez un programme NumPy pour vérifier si deux tableaux sont identiques, élément par élément.

In [36]:
tableau1 = np.array([1, 2, 3])
tableau2 = np.array([1, 2, 3])

print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")

identique = np.array_equal(tableau1, tableau2)
print(f"Les tableaux sont identiques : {identique}")

Tableau 1 : [1 2 3]
Tableau 2 : [1 2 3]
Les tableaux sont identiques : True


37. Écrivez un programme NumPy pour créer un tableau unidimensionnel de quarante valeurs générées pseudo-aléatoirement entre 0 et 1 (distribution uniforme).

In [37]:
tableau = np.random.uniform(0, 1, 40)
print(f"Tableau unidimensionnel de quarante valeurs générées pseudo-aléatoirement entre 0 et 1 :\n{tableau}")

Tableau unidimensionnel de quarante valeurs générées pseudo-aléatoirement entre 0 et 1 :
[0.83602853 0.68397166 0.34306688 0.80609166 0.68730368 0.08484984
 0.88429192 0.22058959 0.96605714 0.91517782 0.07810312 0.22066199
 0.19675265 0.87901767 0.13961739 0.96587836 0.90061243 0.53164425
 0.05442016 0.53140233 0.15926373 0.32921307 0.72169841 0.97410697
 0.65371206 0.49956732 0.09507578 0.25056679 0.06713045 0.58727628
 0.30090125 0.69463875 0.26819787 0.39746531 0.03523205 0.69776357
 0.88221426 0.40176629 0.84613389 0.31878862]
