# **Exercices Fondamentaux NumPy**

1. Écrivez un programme NumPy pour obtenir la version de NumPy et afficher la configuration de compilation de NumPy.

In [1]:
import numpy as np
print(f"Version de NumPy : {np.__version__}")
print("\nConfiguration de compilation de NumPy :")
print(np.show_config())

Version de NumPy : 2.2.5

Configuration de compilation de NumPy :
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/v

c:\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


2. Écrivez un programme NumPy pour obtenir de l'aide sur la fonction d'addition (add).

In [2]:
print("\nAide sur la fonction d'addition (add) :")
print(help(np.add))


Aide sur la fonction d'addition (add) :
Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc resu

3. Écrivez un programme NumPy pour tester si aucun des éléments d’un tableau donné n’est égal à zéro.

In [3]:
tableau_donne = np.array([1, 2, 3, 4, 5])
print(f"Tableau 1 : {tableau_donne}")
print(f"Aucun élément n'est nul : {np.all(tableau_donne != 0)}")

Tableau 1 : [1 2 3 4 5]
Aucun élément n'est nul : True


4. Écrivez un programme NumPy pour tester si un des éléments d’un tableau donné est non nul.

In [4]:
tableau_donne = np.array([0, 0, 3, 0, 0])
print(f"Tableau 1 : {tableau_donne}")
print(f"Des éléments sont non nuls : {np.any(tableau_donne != 0)}")

Tableau 1 : [0 0 3 0 0]
Des éléments sont non nuls : True


5. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont finies (ni infinies, ni NaN).

In [5]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test de finitude (isinf ou isnan sont Faux) : {np.isfinite(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test de finitude (isinf ou isnan sont Faux) : [ True  True False False False  True]


6. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs sont infinies (positives ou négatives).

In [6]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test d'infini (isinf) : {np.isinf(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test d'infini (isinf) : [False False False  True  True False]


7. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont des NaN (Not a Number).

In [7]:
tableau_donne = np.array([1, 0, np.nan, np.inf, -np.inf, 5])
print(f"Tableau : {tableau_donne}")
print(f"Test de NaN (isnan) : {np.isnan(tableau_donne)}")

Tableau : [  1.   0.  nan  inf -inf   5.]
Test de NaN (isnan) : [False False  True False False False]


8. Écrivez un programme NumPy pour tester, élément par élément, si les valeurs d’un tableau sont complexes ou réelles. Testez aussi si une valeur donnée est un scalaire.

In [8]:
tableau_donne = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(f"Tableau : {tableau_donne}")
print(f"Test de complexité (iscomplex) : {np.iscomplex(tableau_donne)}")
print(f"Test de réels (isreal) : {np.isreal(tableau_donne)}")
# Test de scalaires pour chaque élément
print(f"Test de scalaires (isscalar) : {[np.isscalar(x) for x in tableau_donne]}")

Tableau : [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Test de complexité (iscomplex) : [ True False False False False  True]
Test de réels (isreal) : [False  True  True  True  True False]
Test de scalaires (isscalar) : [True, True, True, True, True, True]


9. Écrivez un programme NumPy pour tester si deux tableaux sont égaux, élément par élément, dans une certaine tolérance.

In [9]:
print("Tester si deux tableaux sont égaux élément par élément avec une tolérance :")
tableau1 = np.array([1.0, 2.0, 3.0])
tableau2 = np.array([1.0, 2.0, 3.0001])
tolerance = 0.001
print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")
print(f"Égalité avec tolérance {tolerance} : {np.allclose(tableau1, tableau2, atol=tolerance)}")

Tester si deux tableaux sont égaux élément par élément avec une tolérance :
Tableau 1 : [1. 2. 3.]
Tableau 2 : [1.     2.     3.0001]
Égalité avec tolérance 0.001 : True


10. Écrivez un programme NumPy pour effectuer une comparaison élémentaire (supérieur, supérieur_ou_égal, inférieur, inférieur_ou_égal) entre deux tableaux.

In [10]:
tableau1 = np.array([1, 2, 3])
tableau2 = np.array([4, 5, 6])
print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")
print(f"Supérieur : {np.greater(tableau1, tableau2)}")
print(f"Supérieur ou égal : {np.greater_equal(tableau1, tableau2)}")
print(f"Inferieur : {np.less(tableau1, tableau2)}")
print(f"Inferieur ou égal : {np.less_equal(tableau1, tableau2)}")

Tableau 1 : [1 2 3]
Tableau 2 : [4 5 6]
Supérieur : [False False False]
Supérieur ou égal : [False False False]
Inferieur : [ True  True  True]
Inferieur ou égal : [ True  True  True]


11. Écrivez un programme NumPy pour effectuer une comparaison élémentaire (égalité stricte ou dans une tolérance) entre deux tableaux.

In [11]:
tableau1 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
tableau2 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(f"Tableau 1 : {tableau1}")
print(f"Tableau 2 : {tableau2}")

print(f"Égalité stricte : {np.array_equal(tableau1, tableau2)}")

tolerance = 0.00001
print(f"Égalité avec tolérance {tolerance} : {np.allclose(tableau1, tableau2, atol=tolerance)}")

Tableau 1 : [  72   79   85   90  150 -135  120  -10   60  100]
Tableau 2 : [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Égalité stricte : False
Égalité avec tolérance 1e-05 : True


12. Écrivez un programme NumPy pour créer un tableau avec les valeurs 1, 7, 13, 105 et déterminer la taille mémoire qu’il occupe.

In [12]:
tableau = np.array([1, 7, 13, 105])
print(f"Tableau : {tableau}")
print(f"Taille mémoire occupée : {tableau.nbytes} octets")

Tableau : [  1   7  13 105]
Taille mémoire occupée : 32 octets


13. Écrivez un programme NumPy pour créer un tableau de 10 zéros, un autre de 10 uns, et un autre de 10 cinq.

In [13]:
tableau_zeros = np.zeros(10)
tableau_uns = np.ones(10)
tableau_cinq = np.full(10, 5.) # Ou bien np.ones(10) * 5
print(f"Tableau de 10 zéros : {tableau_zeros}")
print(f"Tableau de 10 uns : {tableau_uns}")
print(f"Tableau de 10 cinq : {tableau_cinq}")

Tableau de 10 zéros : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tableau de 10 uns : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Tableau de 10 cinq : [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Écrivez un programme NumPy pour créer un tableau contenant les entiers de 30 à 70.

In [14]:
tableau = np.arange(30, 71)
print(f"Tableau contenant les entiers de 30 à 70 : {tableau}")

Tableau contenant les entiers de 30 à 70 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15. Écrivez un programme NumPy pour créer un tableau contenant uniquement les entiers pairs de 30 à 70.

In [15]:
tableau = np.arange(30, 71, 2)
print(f"Tableau contenant les entiers pairs de 30 à 70 : {tableau}")

Tableau contenant les entiers pairs de 30 à 70 : [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Écrivez un programme NumPy pour créer une matrice identité 3x3.

In [16]:
matrice_identite = np.identity(3)
print(f"Matrice identité 3x3 :\n{matrice_identite}")

Matrice identité 3x3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Écrivez un programme NumPy pour générer un nombre aléatoire entre 0 et 1.

In [17]:
nombre_aleatoire = np.random.normal(0,1, 1)
print(f"Nombre aléatoire entre 0 et 1 : {nombre_aleatoire}")

Nombre aléatoire entre 0 et 1 : [0.56075951]


18. Écrivez un programme NumPy pour générer un tableau de 15 nombres aléatoires selon une distribution normale standard.

In [18]:
nombre_aleatoire = np.random.normal(0,1, 15)
print(f"Tableau de 15 nombres aléatoires selon une distribution normale standard : {nombre_aleatoire}")

Tableau de 15 nombres aléatoires selon une distribution normale standard : [ 0.0846086   0.88283682 -0.01334864 -0.75552283  0.36020277 -1.29415239
 -0.6267933  -0.38931792 -0.52887678  0.38804823  0.61893259 -0.52608513
 -2.0404551   1.71597232 -1.68349649]


19. Écrivez un programme NumPy pour créer un vecteur de valeurs de 15 à 55, en affichant toutes sauf la première et la dernière.

In [19]:
vecteur = np.arange(15, 56)
print(f"Vecteur de valeurs de 15 à 55 : {vecteur}")

vecteur_sans_premier_dernier = vecteur[1:-1]
print(f"Vecteur sans le premier et le dernier élément : {vecteur_sans_premier_dernier}")

Vecteur de valeurs de 15 à 55 : [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Vecteur sans le premier et le dernier élément : [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20. Écrivez un programme NumPy pour créer un tableau 3x4 et itérer sur ses éléments.

In [20]:
tableau = np.arange(10,22).reshape((3, 4))
print(f"Tableau 3x4 :\n{tableau}")

print("Itération sur les éléments du tableau 3x4 :")
for i in np.nditer(tableau):
    print(i, end=' ')

Tableau 3x4 :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Itération sur les éléments du tableau 3x4 :
10 11 12 13 14 15 16 17 18 19 20 21 